lib/inc/internal/path_parser.hpp, lib/inc/internal/simple_config_origin.hpp, lib/inc/internal/token.hpp, lib/inc/internal/tokenizer.hpp, lib/inc/internal/tokens.hpp, lib/inc/internal/values/abstract_config_value.hpp, lib/inc/internal/values/config_boolean.hpp, lib/inc/internal/values/config_double.hpp, lib/inc/internal/values/config_int.hpp, lib/inc/internal/values/config_long.hpp, lib/inc/internal/values/config_null.hpp, lib/inc/internal/values/config_number.hpp, lib/inc/internal/values/config_string.hpp, lib/src/path_parser.cc, lib/src/simple_config_origin.cc, lib/src/token.cc, lib/src/tokenizer.cc, lib/src/tokens.cc, lib/src/values/abstract_config_value.cc, lib/src/values/config_boolean.cc, lib/src/values/config_double.cc, lib/src/values/config_int.cc, lib/src/values/config_long.cc, lib/src/values/config_null.cc, lib/src/values/config_number.cc, lib/src/values/config_string.cc, lib/tests/test_utils.cc, lib/tests/test_utils.hpp, lib/tests/tokenizer_test.cc
A few uses of simple_config_origin showed bad practices of creating a
new shared_ptr of a simple_config_origin from a reference drawn from
another shared_ptr. This can lead to freed memory references. The
shared pointers also didn't use const, allowing for the shared versions
of simple_config_origin to be modified.
Change to passing shared_ptr<const simple_config_origin> everywhere,
and add an alias shared_origin to make that simpler.
=> (maint) Add shared_origin alias for simple_config_origin

lib/CMakeLists.txt, lib/inc/hocon/config_includer.hpp, lib/inc/hocon/config_parse_options.hpp, lib/src/config_parse_options.cc
For now we leave config_includer unimplemented, as it's not being
exercised.
config_parse_options was kept an immutable object because we already
wanted to use a shared_ptr for config_includer, to avoid having to make
it a concrete class, and it keeps the implementation more in-line with
the original.
Copies should be light-weight, but we may reconsider and make this a
mutable class to avoid lots of copies if it's never really shared.
=> (HC-22) Port ConfigParseOptions

.gitignore, lib/CMakeLists.txt, lib/inc/hocon/config_parse_options.hpp, lib/inc/internal/config_document_parser.hpp, lib/inc/internal/nodes/config_node_include.hpp, lib/inc/internal/path_parser.hpp, lib/inc/internal/tokenizer.hpp, lib/src/config_document_parser.cc, lib/src/config_parse_options.cc, lib/src/nodes/config_node_field.cc, lib/src/nodes/config_node_include.cc, lib/src/path_parser.cc, lib/src/tokenizer.cc, lib/tests/CMakeLists.txt, lib/tests/config_document_parser_test.cc
Adds the main parser class, used for the production of ConfigDocuments, which are representations of HOCON files in code.
=> (HC-7) Port the ConfigDocumentParser

README.md
Add build instructions for the readme.
Assume that the required library versions are the same as those in
`peterhuene/puppetcpp`.
Also include a gratuitous ascii art robot. I like to include something visual
in READMEs.
Also add travis and appveyor badges.
=> Readme Build instructions

lib/inc/internal/config_parser.hpp, lib/src/simple_config_origin.cc
This commit changes the definition of simple_config_origin::append_comments
to match its declaration. In addition, several erroneous #include paths
have been fixed in the config_parser header.
=> (maint) Fixup issues with partial ConfigParser implementation

lib/inc/internal/parseable.hpp, lib/inc/internal/simple_includer.hpp, lib/src/parseable.cc, lib/src/simple_includer.cc
These classes are needed by the simple_includer class. Bring in
ParseableNotFound, the NameSource interface and RelativeNameSource.
=> (HC-40) Port parseable_not_found and relative_name_source classes

README.md
Change `make tests` to `make test`.
=> (maint) Fix typo in README

lib/CMakeLists.txt, lib/inc/internal/substitution_expression.hpp, lib/inc/internal/unmergeable.hpp, lib/src/substitution_expression.cc
The first of these commits ports the small Unmergeable interface, which is needed by several other classes down the road.
The second commit ports the SubstitutionExpression class, which is needed by the ConfigReference implementation.
I'm putting this up now rather than waiting until all of ConfigReference is done both to make review more digestible and get quicker feedback on any insanity in this code before I get too deep.
=> (HC-10) Port Unmergeable interface and SubstitutionExpression class

lib/CMakeLists.txt, lib/inc/hocon/config_list.hpp, lib/inc/hocon/config_value.hpp, lib/inc/internal/config_exception.hpp, lib/inc/internal/container.hpp, lib/inc/internal/resolve_context.hpp, lib/inc/internal/resolve_result.hpp, lib/inc/internal/resolve_source.hpp, lib/inc/internal/simple_config_list.hpp, lib/src/simple_config_list.cc, lib/src/values/config_value.cc
In order to port SimpleConfig List, add all the header files that
are needed. This includes the header file for SimpleConfigList and
several other classes that it relies on. At the moment, the header
files for resolve_context, resolve_result, and resolve_source are
just stubs without any methods or instance variables.
Also implements stubs for methods so everything links.
=> (HC-39) Port header files for SimpleConfigList

lib/inc/hocon/config.hpp, lib/inc/hocon/config_value.hpp, lib/inc/internal/values/config_concatenation.hpp, lib/inc/internal/values/config_delayed_merge.hpp, lib/inc/internal/values/config_delayed_merge_object.hpp, lib/inc/internal/values/config_reference.hpp, lib/inc/internal/values/simple_config_object.hpp, lib/src/config.cc, lib/src/values/config_delayed_merge.cc, lib/src/values/config_delayed_merge_object.cc, lib/src/values/config_value.cc, lib/src/values/simple_config_object.cc, lib/tests/concatenation_test.cc, lib/tests/conf_parser_test.cc
A number of fallback and merge overloads were missing, causing merges to
be skipped. Implement them.
=> (HC-54) Implement missing fallback/merge methods

lib/inc/internal/resolve_context.hpp, lib/src/resolve_context.cc, lib/tests/concatenation_test.cc
This is gross and probably super inefficient (lots of copying
unordered_maps around), but mirrors the original pretty closely.
=> (HC-42) Add memoization support to resolve_context

lib/src/values/simple_config_object.cc, lib/tests/concatenation_test.cc, lib/tests/test_utils.hpp
This implements all of the string concatenation tests, and some of the
array and object tests. The full test suite requires us to have all
the accessors for lists and objects implemented, which we don't
yet. Since we're at the end of a sprint, getting this subset done
seemed expedient.
=> Hc 55 concatenation tests

lib/src/tokenizer.cc, lib/tests/concatenation_test.cc, lib/tests/config_substitution_test.cc, lib/tests/test_utils.cc, lib/tests/test_utils.hpp
Add some basic tests for substitution and the relevant helper methods.
Also do a bit of code cleanup including making the needed operators
public and replacing some global instance variables with functions
instead (to avoid and error where the variable is not initialized
at the time the tests are run).
=> (HC-52) Add basic config substitution tests

lib/inc/internal/values/simple_config_object.hpp, lib/src/values/simple_config_object.cc
These commits implement `simple_config_object::replace_child` and `simple_config_object::has_descendant`, in addition to fixing a few TODOs.
=> (HC-60) Finish simple_config_object implementation

lib/inc/internal/replaceable_merge_stack.hpp, lib/inc/internal/resolve_source.hpp, lib/inc/internal/values/config_delayed_merge.hpp, lib/inc/internal/values/config_delayed_merge_object.hpp, lib/src/config_parser.cc, lib/src/resolve_source.cc, lib/src/values/config_delayed_merge.cc, lib/src/values/config_delayed_merge_object.cc, lib/src/values/config_value.cc, lib/tests/test_utils.cc
This finishes up the work on config_parser::parse_object. Also included is the resolve_substitutions for config_delayed_merge, which was necessary to finish this work.
=> (HC-68) Finish config_parser::parse_object

lib/src/resolve_context.cc, lib/src/simple_includer.cc
When attempting to compile on my system, both of these moves caused the error "moving a temporary object prevents copy elision." After removing the offending moves, the project compiles and all the tests pass.
=> (maint) Fixed a couple of misused moves.

lib/inc/hocon/config_object.hpp, lib/inc/internal/values/config_delayed_merge_object.hpp, lib/inc/internal/values/simple_config_object.hpp, lib/src/values/config_delayed_merge_object.cc, lib/src/values/config_object.cc, lib/src/values/simple_config_object.cc
This commit implements the `new_copy` and `attempt_peek_with_partial_resolve`
methods of the config_delayed_merge_object class.
=> (HC-59) Finish config_delayed_merge_object implementation

lib/tests/conf_parser_test.cc, lib/tests/config_substitution_test.cc
Add "(pending)" to test cases expected to fail to make the ctest
output more redable.
=> (maint) Mark pending tests in title

lib/inc/hocon/config_object.hpp, lib/inc/internal/config_parser.hpp, lib/src/config_parser.cc, lib/tests/conf_parser_test.cc, lib/tests/config_substitution_test.cc, lib/tests/test_utils.cc
This implements create_value_under_path() in the config_parser. Tests that previously failed due to this method not existing now either pass or fail due to unrelated bugs (see HC-78).
We should decide on the best format for marking known test failures. I used "(pending <ticket_number>)" where a ticket had been made, and just "(pending)" otherwise. But this is not consistent throughout at the moment.
=> (HC-66) Implement create_value_under_path()

lib/CMakeLists.txt, lib/inc/hocon/config.hpp, lib/inc/hocon/config_value_factory.hpp, lib/src/config.cc, lib/src/config_value_factory.cc, lib/tests/CMakeLists.txt, lib/tests/config_value_factory_test.cc
This class is used to turn C++ types into config_values. The types it
can accept are limited by the bounded types of the boost::variant used
when unwrapping config_values.
=> (HC-36) Implement ConfigValueFactory API and tests

lib/inc/hocon/config.hpp, lib/inc/internal/values/simple_config_object.hpp, lib/src/config.cc, lib/tests/CMakeLists.txt, lib/tests/config_test.cc
This commit implements the various get_list methods for supported types,
using a templated backing function which will throw exceptions if the
list is not homogeneous and of the desired type.
=> (HC-75) Implement config::get_*_list methods.

lib/inc/hocon/program_options.hpp, lib/tests/CMakeLists.txt, lib/tests/program_options.cc
This adds a `hocon::program_options` namespace with a `parse_hocon`
function. This function can be used the same as any of the normal
`program_options` parsers to generate config values, except it takes
as its input a hocon `shared_config` object.
HOCON allows representing certain data structures that
`boost::program_options` can not - specifically hashes inside arrays
cause trouble. We try to reprsent these when possible, (using a syntax
that treats the array index as a "key"), but defining actual
`po::options_description` sets that can represent these is Hard (if
not impossible).
=> (FACT-1456) Add utility to wrap hocon in boost::program_options

lib/inc/hocon/config.hpp, lib/inc/hocon/config_exception.hpp, lib/inc/hocon/config_value.hpp
This fix replaces "using leatherman::locale::_" references in cpp-hocon
header files. Placed in headers, these declarations pollute the namespace
of components, like facter, that include these headers.
=> (maint) Fix i18n support and header file declarations

CMakeLists.txt, lib/inc/hocon/config.hpp, lib/inc/hocon/types.hpp, lib/src/config.cc, lib/tests/config_test.cc, lib/tests/fixtures/test01.conf
This implements parsing durations with the aid of boost::chrono::durations. There is a lot of converting back and forth between them, but this seemed the easiest way to handle the type system, short of writing my own custom type.
=> (HC-62) Implement duration parsing

lib/inc/hocon/config.hpp, lib/src/config.cc, lib/tests/config_test.cc
Returning parsed durations as doubles was not supported in the original Java. Due to overflow risks and the fact that it probably has very few use cases, this removes it form the C++ port.
=> (maint) Remove the ability to return durations as doubles

lib/inc/hocon/config_object.hpp, lib/inc/hocon/program_options.hpp, lib/inc/internal/values/config_delayed_merge_object.hpp, lib/inc/internal/values/simple_config_object.hpp, lib/tests/program_options.cc
Parsing more complicated HOCON structures (e.g. a list of HOCON objects) into boost::program_options does not work very well. This allows `program_options` to ignore keys not specified in the `options_description`, so that they can instead be handled specially.
The second commit adds a useful method to the public API of config_object, to make interacting with objects easier. This method already existed in the most common concrete implementation of the abstract class; this makes the method publicly accessible without casting.
=> (maint) Allow unregistered options in boost::program_options interface

lib/inc/internal/parseable.hpp, lib/src/config.cc, lib/src/config_document_factory.cc, lib/src/parseable.cc, lib/src/simple_includer.cc, lib/tests/conf_parser_test.cc, locales/cpp-hocon.pot
Including a file from another file caused a crash because we were
creating a shared_ptr from a `parseable` value. The include context
assumes the parseable it's created from will will continue to exist,
meaning we can't copy parseables. Fix instances where we were creating
copies of parseables.
Fixes #75.
=> (maint) Fix include file from file

CMakeLists.txt, lib/tests/CMakeLists.txt
When using leatherman::locale, it is necessary to also link against
boost::locale. On OSX, this further requires linking against the iconv
library.
@MikaelSmith would you mind looking over this and seeing if any of the added bits jump out at you as being definitely unnecessary. This went through enough iterations that I think some things may have been added that are actually irrelevant (and if you find any, I'd love to hear why they're not needed. Still trying to get the full picture on this stuff).
=> (maint) Fix linking errors when building with Leatherman locale

CMakeLists.txt, lib/tests/CMakeLists.txt
This has been run against a full platform set, with successful builds on all of them. Before this can be included in puppet-agent, Facter will need to be updated with similar conditionals around boost::locale.
=> (maint) Fix linking errors on AIX, Solaris, Cisco, and Windows

lib/src/config_document_parser.cc
This clears up the error reported here: https://github.com/puppetlabs/cpp-hocon/issues/80
=> (maint) Fix uninitialized variable error 

README.md
Since leatherman is no longer a submodule for this project, this commit
removes that step from the readme since it's no longer required.
=> (maint) Remove step that mentions submodules

CMakeLists.txt
This version includes a fix to allow cpp-hocon to build with native clang on older OSX and FreeBSD platforms.
=> (packaging) Bump version to 0.1.5

lib/src/simple_includer.cc
Fixes #95 : substitution inside the file should work without the full
path where they are included.
=> Resolve included files before including them

lib/inc/internal/values/config_delayed_merge_object.hpp, lib/src/values/config_delayed_merge_object.cc, lib/src/values/simple_config_object.cc, lib/tests/config_substitution_test.cc
According to documentation: https://github.com/lightbend/config/blob/master/HOCON.md#examples-of-self-referential-substitutions
```
A self-reference resolves to the value "below" even if it's part of a path expression. So for example:
foo : { a : { c : 1 } }
foo : ${foo.a}
foo : { a : 2 }
Here, ${foo.a} would refer to { c : 1 } rather than 2 and so the final merge would be { a : 2, c : 1 }.
Recall that for a field to be self-referential, it must have a substitution or value concatenation as its value. If a field has an object or array value, for example, then it is not self-referential even if there is a reference to the field itself inside that object or array.
```
But I'm getting crash in cases below:
```
"a": {"b": 27},
"obj": ${a}
"val": ${obj.b}
a = {aa = mama}
b = ${a} { bb = mia } …
```
=> Fixed Self-Reference Substitution

lib/src/parseable.cc
With boost 1.67, boost/thread/tss.hpp introduces an unused symbol
warning in puppet-agent (https://github.com/puppetlabs/puppet-agent/pull/1482), halting a build with -Werror: disable that
warning temporarily around this file.
=> (PA-2055) Disable unused warnings for boost::thread

lib/inc/hocon/types.hpp
With boost 1.67, boost/variant.hpp introduces address and (in gcc 6+)
nonnull-compare warnings; Quiet these to allow successful builds with
-Werror. This supports https://github.com/puppetlabs/puppet-agent/pull/1482.
=> (PA-2055) Disable warnings for boost::variant

.travis.yml, CMakeLists.txt
Previously, we had only static artifacts. This was causing
difficulties with running Facter in travis, since Alpine's static
boost libraries are not able to be linked into a shared library, which
Facter requires.
=> (maint) Build dynamic artifact for travis 

.travis.yml
Previously, we had only static artifacts. This was causing
difficulties with running Facter in travis, since Alpine's static
boost libraries are not able to be linked into a shared library, which
Facter requires.
=> (maint) Build dynamic artifact for travis

CMakeLists.txt
Fixes #118. Boost.Filesystem [is not](http://www.boost.org/doc/libs/release/more/getting_started/unix-variants.html#header-only-libraries) a header-only library.
=> Unbreak build with Boost 1.72

lib/src/path.cc, lib/src/tokenizer.cc
This is needed to build with Boost 1.73.0, to fix these errors:
```
lib/src/path.cc: In static member function 'static bool hocon::path::has_funky_chars(const string&)':
lib/src/path.cc:176:25: error: 'find_if' was not declared in this scope; did you mean 'boost::mpl::find_if'?
176 |         auto bad_char = find_if(s.begin(), s.end(), [] (char c) {
|                         ^~~~~~~
lib/src/tokenizer.cc: In member function 'void hocon::token_iterator::pull_escape_sequence(std::string&, std::string&)':
lib/src/tokenizer.cc:310:42: error: 'narrow' is not a member of 'boost::nowide'
310 |                 parsed += boost::nowide::narrow(buffer);
|                                          ^~~~~~
```
=> (build) Add missing headers

CMakeLists.txt
In case the locales on the system fails(due to gconv, or something
else), leatherman will use boost::format and boost::regex, to create %N%
style formatting. 'regex' is only included in CMakeLists.txt if locales
are not enabled, but if they fail, 'regex' will be required
This PR adds 'regex' to BOOST_COMPONENTS regardless if leatherman uses
locales, as an extra check in case the locales are enabled but fail.
=> (maint) Add regex backup if locales fail

.github/workflows/ci_checks.yaml, .github/workflows/release.yaml
The Checkout GitHub Action v3 uses Node 16, which hit end-of-life on September 11, 2023.
This commit updates all instances of the Checkout Action from v3 to v4.
=> (PA-5800) Update Checkout GitHub Action
